# Generated by Django 3.2 on 2021-04-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200, verbose_name='IP address')),
                ('log_data', models.CharField(max_length=200)),
                ('http_method', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200)),
                ('response_code', models.CharField(max_length=200)),
                ('response_size', models.CharField(max_length=200)),
            ],
        ),
    ]
