# Generated by Django 3.2 on 2021-04-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_mgmt", "0002_auto_20210419_1850"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parser",
            old_name="http_method",
            new_name="HTTP_method",
        ),
        migrations.RenameField(
            model_name="parser",
            old_name="uri",
            new_name="URI",
        ),
    ]
