# Generated by Django 3.2 on 2021-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_mgmt", "0003_auto_20210421_1203"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApacheLogs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.CharField(max_length=200, verbose_name="IP address")),
                ("log_date", models.DateTimeField(default=None, verbose_name="Log date")),
                ("HTTP_method", models.CharField(max_length=200)),
                ("URI", models.CharField(max_length=200)),
                ("response_code", models.IntegerField(verbose_name="Response code")),
                ("response_size", models.IntegerField(verbose_name="Response size")),
                ("referer", models.CharField(default=None, max_length=200, verbose_name="Referer")),
                ("user_agent", models.CharField(default=None, max_length=200, verbose_name="User Agent")),
            ],
        ),
        migrations.DeleteModel(
            name="Parser",
        ),
    ]
