# Generated by Django 3.2 on 2021-04-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_mgmt", "0004_auto_20210421_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apachelogs",
            name="response_size",
            field=models.CharField(max_length=200),
        ),
    ]
