# Generated by Django 3.2 on 2021-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_mgmt', '0005_alter_apachelogs_response_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apachelogs',
            name='HTTP_method',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='apachelogs',
            name='URI',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='apachelogs',
            name='log_date',
            field=models.DateTimeField(db_index=True, default=None, verbose_name='Log date'),
        ),
        migrations.AlterField(
            model_name='apachelogs',
            name='referer',
            field=models.CharField(default=None, max_length=400, verbose_name='Referer'),
        ),
        migrations.AlterField(
            model_name='apachelogs',
            name='response_code',
            field=models.IntegerField(db_index=True, verbose_name='Response code'),
        ),
        migrations.AlterField(
            model_name='apachelogs',
            name='user_agent',
            field=models.CharField(default=None, max_length=400, verbose_name='User Agent'),
        ),
    ]
